language: bash

dist: xenial

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S+)?$/ # build all tags in form of semver
  - travis # debugging of .travis.yml

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-venv

env:
  - BASH_VERSION="4.4.23"
  - BASH_VERSION="5.0.11"

cache:
  directories:
    - ${HOME}/.peru

before_install:
  - python3 --version
  - python3 -m venv env
  - source env/bin/activate
  - python --version
  - python -m pip --version
  - python -m pip install --upgrade pip
  - pip install peru

install:
  - peru sync

before_script:
  - docker pull bash:${BASH_VERSION}
  - docker run bash:${BASH_VERSION} --version

script:
  # test needs to be run in docker, because we need to test it under different versions of bash
  - docker run -v ${PWD}:${PWD} -w ${PWD} bash:${BASH_VERSION} ./tests.sh --install-deps

after_success:
  - sed -i "s/<<VERSION>>/${TRAVIS_TAG}/g" tpcp
  - tar cvzf tpcp.tar.gz vendor libs tpcp LICENSE

deploy:
  provider: releases
  api_key:
    secure: WEAQvPbsdl/1sI5UBRhVIDBbD7rCeR/VdteSkUzm40y/aoTU2DTDKIus78WgUfug/NBkPf5a5BTCl1zMdvy4vHuvTz3S3V7mHWwY2hrrFdz9NdaEqa03pQqx8NgusWGIcbbcN0oK9C0HGssex1Ma/ZD3kP7oLaUaB4e5UoZvVQJCJFKI3GghEYXw0CG5Vmv0W3KqX5Js/eqPkcZmQohUWyyGbs2Z5zTcw9kAI6BtMhfE59AJXHechRluQlUxxYcaw71HwJO1ryjXqVLG3ukMDyNdcUCy97dFDnv5Wy+lYgPRYEoWGH3Eypjizw1TESBKJ+v94HqLqPlFTDIeb89p3UWWsRorqxHs9vE+S6nTQHm1JiuZ2y9dl9PqZAMrGbHwiX4ZU4Xe3DLgz0oLzr77RgHZDYmXY/POsw0zXNTNJGaAN7p/9ffKVdluhqRYdCBDnIwocFd4wngA/i1/dLetaBZvzA4YC3HWzB0idezsATquLsZSlaYLBVOZzwMIm3I89B9GG+e+mDe9XOSKehUwC7SepTPimvCZ38cuHyVCsP6pVB99YH9e7pZUiAv6Xr433ovlkjkAko/VJkw+7Y1EE1eCD4yCUXdWOfKYSO6G+OEEpXkxN+/eoHL511TTvHtvrn53a58xuHUZsIjeHj9DNF5zCnPXGaQM92AyQhtJkSk=
  file:
    - tpcp.tar.gz
  skip_cleanup: true
  on:
    repo: Hologos/tpcp
    tags: true
  draft: true
  name: "tpcp ${TRAVIS_TAG}"
