#! /usr/bin/env bash

function tpcp::inputparser::parse_transport_list() {
    local transport_list="${1}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   transport_list=${transport_list}"

    if ! [[ "${transport_list}" =~ [A-Z0-9] ]]; then
        tpcp::utils::terminate "Transport list cannot be empty."
    fi

    if tpcp::utils::contains_duplicates "${transport_list}"; then
        tpcp::utils::terminate "Transport list cannot have duplicates."
    fi

    local transport=""

    for transport in ${transport_list}; do
        logger::log "${TPCP_CURRENT_LABEL}" "D" "Validating transport ${transport}."

        if ! [[ "${transport}" =~ ^[A-Z0-9]{3}K[A-Z0-9]{6}$ ]]; then
            tpcp::utils::terminate "'${transport}' is not a valid transport name."
        fi

        IP_TRANSPORT_LIST+=( "${transport}" )
    done
}

function tpcp::inputparser::parse_system_list() {
    local system_list="${1}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   system_list=${system_list}"

    if ! [[ "${system_list}" =~ [A-Z0-9] ]]; then
        tpcp::utils::terminate "System list cannot be empty."
    fi

    if tpcp::utils::contains_duplicates "${system_list}"; then
        tpcp::utils::terminate "System list cannot have duplicates."
    fi

    local system=""

    for system in ${system_list}; do
        logger::log "${TPCP_CURRENT_LABEL}" "D" "Validating system ${system}."

        if ! [[ "${system}" =~ ^[A-Z0-9]{3}[0-9]{3}$ ]]; then
            tpcp::utils::terminate "'${system}' is not a valid system name."
        fi

        IP_SYSTEM_LIST+=( "${system}" )
    done
}

function tpcp::inputparser::parse_action_list() {
    local action_list="${1}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   action_list=${action_list}"

    if ! [[ "${action_list}" =~ [A-Z0-9] ]]; then
        tpcp::utils::terminate "Action list cannot be empty."
    fi

    if tpcp::utils::contains_duplicates "${action_list}"; then
        tpcp::utils::terminate "Action list cannot have duplicates."
    fi

    local action=""

    for action in ${action_list}; do
        logger::log "${TPCP_CURRENT_LABEL}" "D" "Validating action ${action}."

        if ! [[ "${action}" =~ ^(${SAPTRANSPORT_ACTION_CPY}|${SAPTRANSPORT_ACTION_ADD}|${SAPTRANSPORT_ACTION_IMP}|${SAPTRANSPORT_ACTION_DEL})$ ]]; then
            tpcp::utils::terminate "'${action}' is not a valid action."
        fi

        IP_ACTION_LIST+=( "${action}" )
    done
}
