#! /usr/bin/env bash

TPCP_RENDERER_ALREADY_RENDERED=0

function tpcp::renderer::render() {
    logger::log "T" "Running ${FUNCNAME}():"
    logger::log "T" "   [no-params]"

    tpcp::renderer::__clear_previous_output "${#IP_TRANSPORT_LIST[@]}" "${#IP_SYSTEM_LIST[@]}"

    for transport in "${IP_TRANSPORT_LIST[@]}"; do
        logger::log "T" "Rendering output for transport ${transport}."

        echo
        echo -n "          " # transport name = 10 characters
        echo -n "     "      #    indentation =  5 characters
        echo -n "      "     #    system name =  6 characters
        echo -n "    "       #    indentation =  4 characters

        for action in "${IP_ACTION_LIST[@]}"; do
            echo -n " ${action}"
        done

        echo

        system_index=0

        for system in "${IP_SYSTEM_LIST[@]}"; do
            logger::log "T" "Rendering action results for system ${system}."

            system_index=$(( ${system_index} + 1 ))

            if [[ ${system_index} -eq 1 ]]; then
                echo -n "${transport}" # transport name = 10 characters
            else
                echo -n "          "   # transport name = 10 characters
            fi

            echo -n "     "     # indentation = 5 characters
            echo -n "${system}" # system name = 6 characters
            echo -n "     "     # indentation = 5 characters

            for action in "${IP_ACTION_LIST[@]}"; do
                logger::log "T" "Rendering action result "${action}" for system ${system}."

                local status="$( < "${TPCP_WORK_DIRPATH}/${TPCP_STATUS_FILENAME_PART}.${transport}.${system}.${action}" )" # load

                case "${status}" in
                    "${SAPTRANSPORT_STATUS_INITIAL}" )
                        echo -n " "  #   indentation = 1 character
                        echo -n " "  # action result = 1 character
                        echo -n "  " #   indentation = 2 characters
                    ;;

                    "${SAPTRANSPORT_STATUS_RUNNING}" )
                        echo -n "..."  # action result = 1 character
                        echo -n " "  #   indentation = 1 character
                    ;;

                    "${SAPTRANSPORT_STATUS_FAILED}" )
                        echo -n " "  #   indentation = 1 character
                        echo -n "✖"  # action result = 1 character
                        echo -n "  " #   indentation = 2 characters
                    ;;

                    "${SAPTRANSPORT_STATUS_FINISHED}" )
                        echo -n " "  #   indentation = 1 character
                        echo -n "✔"  # action result = 1 character
                        echo -n "  " #   indentation = 2 characters
                    ;;

                    "${SAPTRANSPORT_STATUS_SKIPPED}" )
                        echo -n " "  #   indentation = 1 character
                        echo -n "-"  # action result = 1 character
                        echo -n "  " #   indentation = 2 characters
                    ;;

                    *)
                        tpcp::utils::terminate "Unknown status '${status}' of action '${action}'."
                esac
            done

            echo
        done
    done

    TPCP_RENDERER_ALREADY_RENDERED=1
}

function tpcp::renderer::__clear_previous_output() {
    local number_of_transports="${1}"
    local number_of_systems="${2}"

    logger::log "T" "Running ${FUNCNAME}():"
    logger::log "T" "   number_of_transports=${number_of_transports}"
    logger::log "T" "   number_of_systems=${number_of_systems}"

    # 1st line: empty
    # 2nd line: actions
    #     rest: system + results
    #
    # repeats for every transport
    local number_of_lines=$(( (1 + 1 + ${number_of_systems} ) * ${number_of_transports} ))

    logger::log "T" "Total number of rendered lines is ${number_of_lines}."

    if [[ ${TPCP_RENDERER_ALREADY_RENDERED} -eq 0 ]]; then
        for i in $(seq ${number_of_lines}); do
            echo
        done

        ansi::deleteLines "${number_of_lines}"
    fi

    ansi::previousLine "${number_of_lines}"
}
