#! /usr/bin/env bash

SAPTRANSPORT_ACTION_CPY="CPY"
SAPTRANSPORT_ACTION_ADD="ADD"
SAPTRANSPORT_ACTION_IMP="IMP"
SAPTRANSPORT_ACTION_DEL="DEL"

SAPTRANSPORT_STATUS_INITIAL="INITIAL"
SAPTRANSPORT_STATUS_RUNNING="RUNNING"
SAPTRANSPORT_STATUS_FAILED="FAILED"
SAPTRANSPORT_STATUS_FINISHED="FINISHED"
SAPTRANSPORT_STATUS_SKIPPED="SKIPPED"

function saptransport::process_transport() {
    local transport="${1}"
    local system_list=("${!2}")
    local action_list=("${!3}")

    logger::log "T" "Running ${FUNCNAME}():"
    logger::log "T" "   transport=${transport}"
    logger::log "T" "   system_list=${system_list[@]}" # TODO: FIX array
    logger::log "T" "   action_list=${action_list[@]}" # TODO: FIX array

    logger::log "D" "Processing transport ${transport}."

    for system in "${system_list[@]}"; do
        saptransport::run_actions_on_system "${transport}" "${system}" "${action_list[@]}" &
    done

    wait
}

function saptransport::run_actions_on_system() {
    local transport="${1}"
    local system="${2}"
    local action_list=("${@:3}")

    logger::log "T" "Running ${FUNCNAME}():"
    logger::log "T" "   transport=${transport}"
    logger::log "T" "   system=${system}"
    logger::log "T" "   action_list=${action_list[@]}" # TODO: FIX array

    logger::log "D" "Running actions for transport ${transport} on system ${system}."

    for action in "${action_list[@]}"; do
        saptransport::run_action_on_system "${transport}" "${system}" "${action}"
    done
}

function saptransport::run_action_on_system() {
    local transport="${1}"
    local system="${2}"
    local action="${3}"

    logger::log "T" "Running ${FUNCNAME}():"
    logger::log "T" "   transport=${transport}"
    logger::log "T" "   system=${system}"
    logger::log "T" "   action=${action}"

    logger::log "D" "Running action ${action} for transport ${transport} on system ${system}."

    tpcp::utils::record_status "${SAPTRANSPORT_STATUS_RUNNING}" "${TPCP_WORK_DIRPATH}" "${transport}" "${system}" "${action}"

    local sid="${system,,}"
    local ssh_user="${sid:0:3}adm"
    local ssh_host="${sid:0:3}00"
    local ssh_port="22"

    case "${action}" in
        "${SAPTRANSPORT_ACTION_CPY}" )
            local sleep_duration=$(( ${RANDOM} % 10 + 1 ))
            local rc_random=$(( ${RANDOM} % 7 ))
            local command="sleep '${sleep_duration}'; [ '${rc_random}' -ne 0 ]"
        ;;

        "${SAPTRANSPORT_ACTION_ADD}" )
            local sleep_duration=$(( ${RANDOM} % 2 + 1 ))
            local rc_random=$(( ${RANDOM} % 7 ))
            local command="sleep '${sleep_duration}'; [ '${rc_random}' -ne 0 ]"
        ;;

        "${SAPTRANSPORT_ACTION_IMP}" )
            local sleep_duration=$(( ${RANDOM} % 20 + 1 ))
            local rc_random=$(( ${RANDOM} % 7 ))
            local command="sleep '${sleep_duration}'; [ '${rc_random}' -ne 0 ]"
        ;;

        "${SAPTRANSPORT_ACTION_DEL}" )
            local sleep_duration=$(( ${RANDOM} % 2 + 1 ))
            local rc_random=$(( ${RANDOM} % 7 ))
            local command="sleep '${sleep_duration}'; [ '${rc_random}' -ne 0 ]"
        ;;

        * )
            tpcp::utils::terminate "'${action}' is not a valid action." # assert
    esac

    local rc=0

    tpcp::ssh::run_command  \
        "${ssh_user}"       \
        "${ssh_host}"       \
        "${ssh_port}"       \
        "${command}"        \
    || rc=1

    if [[ ${rc} -eq 0 ]]; then
        tpcp::utils::record_status "${SAPTRANSPORT_STATUS_FINISHED}" "${TPCP_WORK_DIRPATH}" "${transport}" "${system}" "${action}"

        return
    else
        tpcp::utils::record_status "${SAPTRANSPORT_STATUS_FAILED}" "${TPCP_WORK_DIRPATH}" "${transport}" "${system}" "${action}"

        return 1
    fi
}
