#! /usr/bin/env bash

declare -A SAPTRANSPORT_HOSTNAMES_MAP
declare -A SAPTRANSPORT_DOMAIN_CONTROLLERS_MAP

readonly SAPTRANSPORT_ACTION_CPY="CPY"
readonly SAPTRANSPORT_ACTION_ADD="ADD"
readonly SAPTRANSPORT_ACTION_IMP="IMP"
readonly SAPTRANSPORT_ACTION_DEL="DEL"

readonly SAPTRANSPORT_STATUS_INITIAL="INITIAL"
readonly SAPTRANSPORT_STATUS_RUNNING="RUNNING"
readonly SAPTRANSPORT_STATUS_FAILED="FAILED"
readonly SAPTRANSPORT_STATUS_FINISHED="FINISHED"
readonly SAPTRANSPORT_STATUS_SKIPPED="SKIPPED"
readonly SAPTRANSPORT_STATUS_WAITING="WAITING"

readonly SAPTRANSPORT_STATUS_FILENAME_PART="saptransport_status"
readonly SAPTRANSPORT_ABORT_FILENAME="saptransport_abort"
readonly SAPTRANSPORT_DOMAIN_CONTROLLER_FILENAME_PART="saptransport_domain_controller"
readonly SAPTRANSPORT_DOMAIN_CONTROLLER_ABORT_FILENAME="saptransport_domain_controller_abort"
readonly SAPTRANSPORT_NOT_FINISHED="saptransport_not_finished"

function saptransport::process_transport() {
    local transport="${1}"
    local system_list=("${!2}")
    local action_list=("${!3}")

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   transport=${transport}"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   system_list=${system_list[*]}"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   action_list=${action_list[*]}"

    logger::log "${TPCP_CURRENT_LABEL}" "D" "Processing transport ${transport}."

    local system=""

    for system in "${system_list[@]}"; do
        saptransport::__run_actions_on_system "${transport}" "${system}" "${action_list[@]}" &
    done

    wait

    local not_yet_started_filepath="${TPCP_WORK_DIRPATH}/${SAPTRANSPORT_NOT_FINISHED}"

    rm -f "${not_yet_started_filepath}" \
        || tpcp::utils::terminate "Cannot remove file ${not_yet_started_filepath}."
}

function saptransport::__run_actions_on_system() {
    local transport="${1}"
    local system="${2}"
    local action_list=("${@:3}")

    # setup separate log file for actions on system
    TPCP_CURRENT_LABEL="${transport}-${system}"

    logger::init "${TPCP_CURRENT_LABEL}" "${TPCP_LOGGER_LEVEL}" "${TPCP_LOG_DIRPATH}/${transport}-${system}.log"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   transport=${transport}"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   system=${system}"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   action_list=${action_list[*]}"

    logger::log "${TPCP_CURRENT_LABEL}" "I" "Running actions for transport ${transport} on system ${system}."

    local action=""

    for action in "${action_list[@]}"; do
        saptransport::__run_action_on_system "${transport}" "${system}" "${action}" || {
            logger::log "E" "Processing transport ${transport} on system ${system} failed while executing action ${action}."
            logger::log "${TPCP_CURRENT_LABEL}" "E" "Processing transport ${transport} on system ${system} failed while executing action ${action}."

            return 1
        }
    done

    logger::log "I" "All actions for transport ${transport} on system ${system} were successfully completed."
    logger::log "${TPCP_CURRENT_LABEL}" "I" "All actions for transport ${transport} on system ${system} were successfully completed."
}

function saptransport::__run_action_on_system() {
    local transport="${1}"
    local system="${2}"
    local action="${3}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   transport=${transport}"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   system=${system}"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   action=${action}"

    if [[ -e "${TPCP_WORK_DIRPATH}/${SAPTRANSPORT_ABORT_FILENAME}" ]]; then
        logger::log "${TPCP_CURRENT_LABEL}" "W" "Aborting the program. Skipping all actions for transport ${transport} on system ${system}."

        exit 1
    fi

    logger::log "${TPCP_CURRENT_LABEL}" "I" "Running action ${action} for transport ${transport} on system ${system}."

    saptransport::record_status "${SAPTRANSPORT_STATUS_RUNNING}" "${transport}" "${system}" "${action}"

    # shellcheck disable=SC2155
    local sid="$(saptransport::__get_sid "${system}")"
    # shellcheck disable=SC2155
    local client="$(saptransport::__get_client "${system}")"
    # shellcheck disable=SC2155
    local transport_label="$(saptransport::__get_transport_label "${transport}")"

    if ! saptransport::__hostname_exists "${sid}"; then
        logger::log "${TPCP_CURRENT_LABEL}" "E" "Hostname for SID ${sid} not found."

        saptransport::record_status "${SAPTRANSPORT_STATUS_FAILED}" "${transport}" "${system}" "${action}"

        return 1
    fi

    local ssh_user="${sid,,}adm"
    local ssh_host="${SAPTRANSPORT_HOSTNAMES_MAP[${sid}]}"
    local ssh_port="22"
    local ssh_commands=()

    local domain_controller="${SAPTRANSPORT_DOMAIN_CONTROLLERS_MAP[${sid}]}"
    local rc_threshold=0

    case "${action}" in
        "${SAPTRANSPORT_ACTION_CPY}" )
            # copies transport from source system

            # shellcheck disable=SC2155
            local sid_source="$(saptransport::__get_sid_from_transport "${transport}")"

            local ssh_target_user="${ssh_user}"
            local ssh_target_host="${ssh_host}"
            local ssh_target_port="${ssh_port}"

            local ssh_user="${sid_source,,}adm"
            local ssh_host="${SAPTRANSPORT_HOSTNAMES_MAP[${sid_source}]}"
            local ssh_port="22"

            local domain_controller_source="${SAPTRANSPORT_DOMAIN_CONTROLLERS_MAP[${sid_source}]}"
            local selected_system

            selected_system="$(saptransport::__get_system_from_requested_transport_domain "${domain_controller}" "${IP_SYSTEM_LIST[@]}")" || { \
                saptransport::record_status "${SAPTRANSPORT_STATUS_FAILED}" "${transport}" "${system}" "${action}"

                tpcp::utils::terminate "Cannot find system from requested transport domain ${domain_controller}."
            }

            # copying transport files within a transport domain
            if [[ "${domain_controller_source}" == "${domain_controller}" ]]; then
                logger::log "${TPCP_CURRENT_LABEL}" "N" "No need to copy transport files, they are reachable within the transport domain (source=DOMAIN_${domain_controller_source}, target=DOMAIN_${domain_controller})."

                saptransport::record_status "${SAPTRANSPORT_STATUS_SKIPPED}" "${transport}" "${system}" "${action}"

                return 0

            # copying transport files across transport domains but this is not selected system
            elif [[ "${system}" != "${selected_system}" ]]; then
                logger::log "${TPCP_CURRENT_LABEL}" "N" "Transport files will be copied only to selected system ${selected_system} (source=DOMAIN_${domain_controller_source}, target=DOMAIN_${domain_controller})."

                logger::log "${TPCP_CURRENT_LABEL}" "N" "Waiting for transport copy to finish on selected system ${selected_system}."

                saptransport::record_status "${SAPTRANSPORT_STATUS_WAITING}" "${transport}" "${system}" "${action}"

                while : ; do
                    sleep 0.2

                    local status

                    status="$(saptransport::read_status "${transport}" "${selected_system}" "${action}")"

                    case "${status}" in
                        "${SAPTRANSPORT_STATUS_FINISHED}" )
                            break
                        ;;

                        "${SAPTRANSPORT_STATUS_FAILED}" )
                            logger::log "${TPCP_CURRENT_LABEL}" "E" "Copying transport files to selected system ${selected_system} failed."

                            saptransport::record_status "${SAPTRANSPORT_STATUS_FAILED}" "${transport}" "${system}" "${action}"

                            return 1
                        ;;

                        "${SAPTRANSPORT_STATUS_SKIPPED}" | "${SAPTRANSPORT_STATUS_WAITING}" )
                            logger::log "${TPCP_CURRENT_LABEL}" "E" "Copying action on selected system ${selected_system} cannot be in this state ${status}."

                            saptransport::record_status "${SAPTRANSPORT_STATUS_FAILED}" "${transport}" "${system}" "${action}"

                            return 1
                        ;;
                    esac
                done

                logger::log "${TPCP_CURRENT_LABEL}" "N" "Transport files were successfully copied to selected system ${selected_system}."

                saptransport::record_status "${SAPTRANSPORT_STATUS_SKIPPED}" "${transport}" "${system}" "${action}"

                return 0
            fi

            # copy to selected system's domain controller instead
            if [[ "${sid}" != "${domain_controller}" ]]; then
                ssh_target_user="${domain_controller,,}adm"
                ssh_target_host="${SAPTRANSPORT_HOSTNAMES_MAP[${domain_controller}]}"
                ssh_target_port="${ssh_port}"

                logger::log "${TPCP_CURRENT_LABEL}" "N" "Changing transport file copy target to domain controller ${domain_controller} (old-target=${sid}, new-target=${domain_controller})."
            fi

            logger::log "${TPCP_CURRENT_LABEL}" "I" "Copying transport files since this is selected system."

            ssh_commands+=("scp -p -o ConnectTimeout=5 -o BatchMode=yes -P ${ssh_target_port} /usr/sap/trans/cofiles/K${transport_label}.${sid_source} ${ssh_target_user}@${ssh_target_host}:/usr/sap/trans/cofiles/")
            ssh_commands+=("scp -p -o ConnectTimeout=5 -o BatchMode=yes -P ${ssh_target_port} /usr/sap/trans/data/R${transport_label}.${sid_source} ${ssh_target_user}@${ssh_target_host}:/usr/sap/trans/data/")
        ;;

        "${SAPTRANSPORT_ACTION_ADD}" )
            ssh_commands+=("/usr/sap/${sid}/SYS/exe/run/tp ADDTOBUFFER ${transport} ${sid} client=${client} pf=/usr/sap/trans/bin/TP_DOMAIN_${domain_controller}.PFL")
        ;;

        "${SAPTRANSPORT_ACTION_IMP}" )
            rc_threshold=4

            ssh_commands+=("/usr/sap/${sid}/SYS/exe/run/tp IMPORT ${transport} ${sid} client=${client} U128 pf=/usr/sap/trans/bin/TP_DOMAIN_${domain_controller}.PFL")
        ;;

        "${SAPTRANSPORT_ACTION_DEL}" )
            ssh_commands+=("/usr/sap/${sid}/SYS/exe/run/tp DELFROMBUFFER ${transport} ${sid} client=${client} pf=/usr/sap/trans/bin/TP_DOMAIN_${domain_controller}.PFL")
        ;;

        * )
            tpcp::utils::terminate "'${action}' is not a valid action." # assert
    esac

    local ssh_command=""

    for ssh_command in "${ssh_commands[@]}"; do
        local rc=0

        tpcp::ssh::run_command                      \
            --rc-threshold="${rc_threshold}"        \
                                                    \
            "${ssh_user}"                           \
            "${ssh_host}"                           \
            "${ssh_port}"                           \
                                                    \
            "${ssh_command}"                        \
                1> >(tpcp::utils::capture_stdout)   \
                2> >(tpcp::utils::capture_stderr)   \
                || rc=${?}

        if [[ ${rc} -gt ${rc_threshold} ]]; then
            logger::log "${TPCP_CURRENT_LABEL}" "E" "There was an error while running action ${action} for transport ${transport} on system ${system}."

            saptransport::record_status "${SAPTRANSPORT_STATUS_FAILED}" "${transport}" "${system}" "${action}"

            return 1
        fi
    done

    saptransport::record_status "${SAPTRANSPORT_STATUS_FINISHED}" "${transport}" "${system}" "${action}"
}

function saptransport::record_status() {
    local status="${1}"
    local transport="${2}"
    local system="${3}"
    local action="${4}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   status=${status}"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   transport=${transport}"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   system=${system}"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   action=${action}"

    local subsequent_action
    local action_found=0
    local last_action=0

    # FIX: set status of subsequent action(s) first to fix the race condition in saptransport::is_all_done()
    if [[ "${status}" == "${SAPTRANSPORT_STATUS_FAILED}" ]]; then
        logger::log "${TPCP_CURRENT_LABEL}" "D" "Changing all statuses of subsequent actions to ${SAPTRANSPORT_STATUS_SKIPPED}."

        for subsequent_action in "${IP_ACTION_LIST[@]}"; do
            last_action=0

            if [[ ${action_found} -eq 0 ]] && [[ "${subsequent_action}" == "${action}" ]]; then # this expects that 2 identical actions cannot exist
                action_found=1
                last_action=1
                continue
            fi

            if [[ ${action_found} -eq 1 ]]; then
                saptransport::record_status "${SAPTRANSPORT_STATUS_SKIPPED}" "${transport}" "${system}" "${subsequent_action}"
            fi
        done
    elif [[ "${status}" == "${SAPTRANSPORT_STATUS_FINISHED}" ]]; then
        logger::log "${TPCP_CURRENT_LABEL}" "D" "Changing status of subsequent action to ${SAPTRANSPORT_STATUS_RUNNING} for finished action."

        for subsequent_action in "${IP_ACTION_LIST[@]}"; do
            last_action=0

            if [[ ${action_found} -eq 0 ]] && [[ "${subsequent_action}" == "${action}" ]]; then # this expects that 2 identical actions cannot exist
                action_found=1
                last_action=1
                continue
            fi

            if [[ ${action_found} -eq 1 ]]; then
                saptransport::record_status "${SAPTRANSPORT_STATUS_RUNNING}" "${transport}" "${system}" "${subsequent_action}"
                break
            fi
        done
    else
        # to pass the assert
        last_action=1
    fi

    # assert
    if [[ ${action_found} -eq 0 ]] && [[ ${last_action} -eq 0 ]]; then
        tpcp::utils::terminate "Action '${action}' was not found, cannot change status of subsequest action(s)."
    fi

    logger::log "${TPCP_CURRENT_LABEL}" "D" "Changing status of ${transport}->${system}->${action} to ${status}."

    local filepath="${TPCP_WORK_DIRPATH}/${SAPTRANSPORT_STATUS_FILENAME_PART}.${transport}.${system}.${action}"
    local filepath_tmp="${filepath}.tmp"

    # FIX: set status of current action as last thing to fix the race condition in saptransport::is_all_done()
    echo -n "${status}" > "${filepath_tmp}" \
        || tpcp::utils::terminate "Cannot record status of ${transport}->${system}->${action} to ${filepath_tmp}."

    mv "${filepath_tmp}" "${filepath}" \
        || tpcp::utils::terminate "Cannot replace ${filepath} with ${filepath_tmp}."
}

function saptransport::read_status() {
    local transport="${1}"
    local system="${2}"
    local action="${3}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   transport=${transport}"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   system=${system}"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   action=${action}"

    logger::log "${TPCP_CURRENT_LABEL}" "D" "Loading status of ${transport}->${system}->${action}."

    local status

    status="$( < "${TPCP_WORK_DIRPATH}/${SAPTRANSPORT_STATUS_FILENAME_PART}.${transport}.${system}.${action}" )" \
        || tpcp::utils::terminate "Cannot load status of ${transport}->${system}->${action}."

    logger::log "${TPCP_CURRENT_LABEL}" "D" "Status of ${transport}->${system}->${action} is '${status}'."

    case "${status}" in
        "${SAPTRANSPORT_STATUS_INITIAL}"    | \
        "${SAPTRANSPORT_STATUS_RUNNING}"    | \
        "${SAPTRANSPORT_STATUS_FAILED}"     | \
        "${SAPTRANSPORT_STATUS_FINISHED}"   | \
        "${SAPTRANSPORT_STATUS_SKIPPED}"    | \
        "${SAPTRANSPORT_STATUS_WAITING}"    )
            echo -n "${status}"
        ;;

        *)
            tpcp::utils::terminate "Unknown status of ${transport}->${system}->${action} is '${status}'."
    esac
}

function saptransport::initialize_statuses() {
    local transport_list=("${!1}")
    local system_list=("${!2}")
    local action_list=("${!3}")

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   transport_list=${transport_list[*]}"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   system_list=${system_list[*]}"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   action_list=${action_list[*]}"

    logger::log "${TPCP_CURRENT_LABEL}" "D" "Initializing all statuses."

    local not_yet_started_filepath="${TPCP_WORK_DIRPATH}/${SAPTRANSPORT_NOT_FINISHED}"

    touch "${not_yet_started_filepath}" \
        || tpcp::utils::terminate "Cannot create file ${not_yet_started_filepath}."

    for transport in "${transport_list[@]}"; do
        for system in "${system_list[@]}"; do
            for action in "${action_list[@]}"; do
                saptransport::record_status "${SAPTRANSPORT_STATUS_INITIAL}" "${transport}" "${system}" "${action}"
            done
        done
    done
}

function saptransport::is_all_done() {
    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   [no-params]"

    local not_yet_started_filepath="${TPCP_WORK_DIRPATH}/${SAPTRANSPORT_NOT_FINISHED}"

    if [[ -e "${not_yet_started_filepath}" ]]; then
        logger::log "${TPCP_CURRENT_LABEL}" "D" "Not yet done, mark file exists ${not_yet_started_filepath}."

        return 1
    fi
}

function saptransport::__get_sid() {
    local system="${1}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   system=${system}"

    echo -n "${system:0:3}"
}

function saptransport::__get_sid_from_transport() {
    local transport="${1}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   transport=${transport}"

    echo -n "${transport:0:3}"
}

function saptransport::__get_client() {
    local system="${1}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   system=${system}"

    echo -n "${system:3}"
}

function saptransport::__get_system_group_name() {
    local sid="${1}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   sid=${sid}"

    echo -n "${sid:0:2}"
}

function saptransport::__get_system_group_role() {
    local sid="${1}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   sid=${sid}"

    echo -n "${sid:2}"
}

function saptransport::__get_transport_label() {
    local transport="${1}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   transport=${transport}"

    echo -n "${transport:4}"
}

function saptransport::__cache_transport_domain_from_sid() {
    local sid="${1}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   sid=${sid}"

    if ! saptransport::__cache_transport_domain "${sid}"; then
        local filepath="${TPCP_WORK_DIRPATH}/${SAPTRANSPORT_DOMAIN_CONTROLLER_ABORT_FILENAME}"

        # creates signal file to abort
        touch "${filepath}" \
            || tpcp::utils::terminate "Cannot create signal file '${filepath}'."

        return 1
    fi

    return 0
}

function saptransport::cache_transport_domains() {
    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   args=${*}"

    logger::log "${TPCP_CURRENT_LABEL}" "I" "Caching all transport domains in parallel."

    local sids

    mapfile -t sids < <(saptransport::__make_sids_unique "${@}")

    logger::log "${TPCP_CURRENT_LABEL}" "D" "Optimized list of SID is '${sids[*]}'."

    local sid

    for sid in "${sids[@]}"; do
        # cache transport domains in parallel
        saptransport::__cache_transport_domain_from_sid "${sid}" &
    done

    wait

    if [[ -e "${TPCP_WORK_DIRPATH}/${SAPTRANSPORT_DOMAIN_CONTROLLER_ABORT_FILENAME}" ]]; then
        tpcp::utils::terminate "Could not cache all domain controllers."
    fi

    # load transport domains here so all background processes have full transport domains map
    local cache_filepath

    for cache_filepath in "${TPCP_WORK_DIRPATH}/${SAPTRANSPORT_DOMAIN_CONTROLLER_FILENAME_PART}."*; do
        local sid="${cache_filepath: -3}"

        SAPTRANSPORT_DOMAIN_CONTROLLERS_MAP[${sid}]="$( < "${cache_filepath}" )" \
            || tpcp::utils::terminate "Cannot load domain controller from file '${cache_filepath}'."

        # TODO: maybe cache domain controller here to prevent unnecessary reading from file in saptransport::__cache_transport_domain()
    done

    logger::log "${TPCP_CURRENT_LABEL}" "I" "Caching all transport domains has finished."
}

function saptransport::__cache_transport_domain() {
    local sid="${1}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   sid=${sid}"

    logger::log "${TPCP_CURRENT_LABEL}" "D" "Caching transport domain for ${sid}."

    if ! saptransport::__hostname_exists "${sid}"; then
        logger::log "${TPCP_CURRENT_LABEL}" "C" "Hostname for SID ${sid} not found."

        return 1
    fi

    local ssh_user="${sid,,}adm"
    local ssh_host="${SAPTRANSPORT_HOSTNAMES_MAP[${sid}]}"
    local ssh_port="22"
    local ssh_command="grep -E -x '^DOMAIN_([A-Z0-9]{3})\$' /usr/sap/trans/bin/DOMAIN.CFG | cut -d '_' -f 2"
    local cache_filepath="${TPCP_WORK_DIRPATH}/${SAPTRANSPORT_DOMAIN_CONTROLLER_FILENAME_PART}.${sid}"

    local rc=0

    tpcp::ssh::run_command                      \
        "${ssh_user}"                           \
        "${ssh_host}"                           \
        "${ssh_port}"                           \
                                                \
        "${ssh_command}"                        \
            1> "${cache_filepath}"              \
            2> >(tpcp::utils::capture_stderr)   \
            || rc=1

    if [[ ${rc} -ne 0 ]]; then
        logger::log "${TPCP_CURRENT_LABEL}" "C" "Cannot get domain controller for ${sid} from ${ssh_user}@${ssh_host}:${ssh_port}."

        return 1
    fi

    local domain_controller

    domain_controller="$( < "${cache_filepath}" )" \
        || tpcp::utils::terminate "Cannot load domain controller from file '${cache_filepath}'."

    logger::log "${TPCP_CURRENT_LABEL}" "D" "Transport domain for ${sid} is ${domain_controller}."

    # cache domain controller as well
    if [[ "${sid}" != "${domain_controller}" ]]; then
        local cache_filepath_domain_controller="${TPCP_WORK_DIRPATH}/${SAPTRANSPORT_DOMAIN_CONTROLLER_FILENAME_PART}.${domain_controller}"

        logger::log "${TPCP_CURRENT_LABEL}" "D" "Caching transport domain for domain controller ${domain_controller}."

        echo -n "${domain_controller}" > "${cache_filepath_domain_controller}"
    fi
}

function saptransport::__hostname_exists() {
    local sid="${1}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   sid=${sid}"

    if ! [[ ${SAPTRANSPORT_HOSTNAMES_MAP[${sid}]+_} ]]; then
        return 1
    fi
}

function saptransport::__get_system_from_requested_transport_domain() {
    local domain_controller="${1}"
    local system_list=("${@:2}") # assert: order of passed array stays always the same

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   domain_controller=${domain_controller}"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   system_list=${system_list[*]}"

    logger::log "${TPCP_CURRENT_LABEL}" "D" "Searching for system from requested transport domain ${domain_controller} (system_list=${system_list[*]})."

    local selected_system

    # doing it this way so it is cross-platform (grep -o works only with GNU grep)
    selected_system="$(echo -n "${system_list[@]}" | tr ' ' "\n" | grep -E "^${domain_controller}[0-9]{3}\$" | head -n 1)" \
        || logger::log "${TPCP_CURRENT_LABEL}" "D" "Searching for domain controller system for requested transport domain ${domain_controller} in system list failed."

    # prefer domain controller
    if [[ "${selected_system}" != "" ]]; then
        logger::log "${TPCP_CURRENT_LABEL}" "D" "Found domain controller system ${selected_system} for requested transport domain ${domain_controller}."

        echo -n "${selected_system}"

        return 0
    fi

    # choose any system from the same transport domain
    logger::log "${TPCP_CURRENT_LABEL}" "D" "Domain controller system from requested transport domain ${domain_controller} not found."
    logger::log "${TPCP_CURRENT_LABEL}" "D" "Searching for any system from requested transport domain ${domain_controller}."

    local system

    for system in "${system_list[@]}"; do
        # shellcheck disable=SC2155
        local sid_discovered="$(saptransport::__get_sid "${system}")"
        local domain_controller_discovered="${SAPTRANSPORT_DOMAIN_CONTROLLERS_MAP[${sid_discovered}]}"

        if [[ "${domain_controller}" == "${domain_controller_discovered}" ]]; then
            logger::log "${TPCP_CURRENT_LABEL}" "D" "Found system ${system} from requested transport domain ${domain_controller}."

            echo -n "${system}"

            return 0
        fi

        logger::log "${TPCP_CURRENT_LABEL}" "D" "System ${system} is not from requested transport domain (requested=${domain_controller}, discovered=${domain_controller_discovered})."
    done

    logger::log "${TPCP_CURRENT_LABEL}" "E" "No system found for requested transport domain ${domain_controller}."

    return 1
}

function saptransport::load_ini_file() {
    local filepath="${1}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   filepath=${filepath}"

    logger::log "${TPCP_CURRENT_LABEL}" "I" "Loading ini file ${filepath}."

    if [[ ! -r "${filepath}" ]]; then
        tpcp::utils::terminate "Cannot read ini file ${filepath}."
    fi

    local line=""
    local line_number=0

    while read -r line; do
        line_number="$(( line_number + 1 ))"

        logger::log "${TPCP_CURRENT_LABEL}" "D" "Reading line #${line_number} '${line}'."

        # skip lines beginning with ; (semicolon)
        # skip empty lines or containing only whitespaces
        if [[ "${line}" =~ ^\; ]] || [[ "${line}" =~ ^[[:space:]]*$ ]]; then
            logger::log "${TPCP_CURRENT_LABEL}" "D" "Skipping line #${line_number} '${line}'."

            continue
        fi

        # SID=hostname
        if ! [[ ${line} =~ ^[A-Z0-9]{3}=(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$ ]]; then
            tpcp::utils::terminate "Malformed ini file ${filepath}, line #${line_number} '${line}'."
        fi

        local sid="${line%=*}"
        local hostname="${line#*=}"

        logger::log "${TPCP_CURRENT_LABEL}" "D" "SID=${sid}"
        logger::log "${TPCP_CURRENT_LABEL}" "D" "hostname=${hostname}"

        SAPTRANSPORT_HOSTNAMES_MAP[${sid}]="${hostname}"
    done < "${filepath}"
}

function saptransport::__make_sids_unique() {
    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME[0]}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   args=${*}"

    logger::log "${TPCP_CURRENT_LABEL}" "D" "Removing duplicate SIDs from the list '${*}'."

    echo -n "${@}" | tr ' ' "\n" | cut -c 1-3 | sort | uniq
}
