#! /usr/bin/env bash

function tpcp::utils::usage() {
    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   [no-params]"

    local fmt_bold="$(ansi --bold --no-restore)"
    local fmt_italic="$(ansi --underline --no-restore)"
    local fmt_reset="$(ansi --reset-attrib)"

    >&2 echo
    >&2 echo "Usage: $0 <transport-list> <system-list> <action-list>"
    >&2 echo
    >&2 echo "    ${fmt_bold}<transport-list>${fmt_reset}"
    >&2 echo "        List of transport names (eg: ABCK000001)."
    >&2 echo
    >&2 echo "    ${fmt_bold}<system-list>${fmt_reset}"
    >&2 echo "        List of system names in form of [SID][CLIENT] (eg: ABC000)."
    >&2 echo
    >&2 echo "    ${fmt_bold}<action-list>${fmt_reset}"
    >&2 echo "        List of actions."
    >&2 echo
    >&2 echo "        ${fmt_italic}Possible values:${fmt_reset}"
    >&2 echo "            ${fmt_bold}${SAPTRANSPORT_ACTION_CPY}${fmt_reset} - copy transport from source system to destination system"
    >&2 echo "            ${fmt_bold}${SAPTRANSPORT_ACTION_ADD}${fmt_reset} - add transport into import queue"
    >&2 echo "            ${fmt_bold}${SAPTRANSPORT_ACTION_IMP}${fmt_reset} - import transport into system"
    >&2 echo "            ${fmt_bold}${SAPTRANSPORT_ACTION_DEL}${fmt_reset} - delete transport from import queue"
    >&2 echo
    >&2 echo "${fmt_italic}Environment variables${fmt_reset}"
    >&2 echo "    ${fmt_bold}TPCP_SYSTEM_FILEPATH${fmt_reset} - filepath to system definition ini file"
    >&2 echo "    ${fmt_bold}TPCP_LOGGER_LEVEL${fmt_reset} - level for logger library (default is I)"
    >&2 echo "    ${fmt_bold}TPCP_LOG_DIRPATH_ROOT${fmt_reset} - dirpath to directory (relative or absolute) where to store logs (default is .)"
}

function tpcp::utils::terminate() {
    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME}():"

    if [[ ${#} -eq 0 ]]; then
        logger::log "${TPCP_CURRENT_LABEL}" "T" "   [no-params]"
    else
        local message="${1}"

        logger::log "${TPCP_CURRENT_LABEL}" "T" "   message=${message}"

        # also print to STDERR
        >&2 echo
        >&2 echo "The program has been terminated due to a critical error:"
        >&2 echo "${message}"

        logger::log "${TPCP_CURRENT_LABEL}" "C" "${message}"
    fi

    exit 1
}

function tpcp::utils::contains_duplicates() {
    local string="${1}"

    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   string=${string}"

    if [[ "$(echo -n "${string}" | tr ' ' "\n" | sort | uniq -d)" != "" ]]; then
        return 0
    fi

    return 1
}

function tpcp::utils::interrupt_trap() {
    logger::log "T" "Running ${FUNCNAME}():"
    logger::log "T" "   [no-params]"

    logger::log "C" "The program is being killed! Killing all background processes."

    # create signal file to stop futher processing
    touch "${TPCP_WORK_DIRPATH}/${SAPTRANSPORT_ABORT_FILENAME}"
}

function tpcp::utils::exit_trap() {
    logger::log "T" "Running ${FUNCNAME}():"
    logger::log "T" "   [no-params]"

    tpcp::render::print_log_location
}

function tpcp::utils::cleanup() {
    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   [no-params]"

    logger::log "${TPCP_CURRENT_LABEL}" "I" "Cleaning up temporary files."

    rm -rf "${TPCP_WORK_DIRPATH}"
}

function tpcp::utils::capture_stdout() {
    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   [no-params]"

    local msg=""

    while read msg; do
        logger::log "${TPCP_CURRENT_LABEL}" "I" "${msg}"
    done
}

function tpcp::utils::capture_stderr() {
    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME}():"
    logger::log "${TPCP_CURRENT_LABEL}" "T" "   [no-params]"

    local msg=""

    while read msg; do
        logger::log "${TPCP_CURRENT_LABEL}" "W" "${msg}"
    done
}
